# Generated by Django 5.0.6 on 2024-05-15 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-created_at",)},
        ),
    ]
