# Generated by Django 5.0.6 on 2024-05-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="meta_measurement",
            field=models.ManyToManyField(to="product.metameasurement"),
        ),
    ]
