# Generated by Django 5.0.6 on 2024-05-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="business_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
