# Generated by Django 5.0.6 on 2024-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_metameasurement_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="meta_measurement",
            field=models.ManyToManyField(
                blank=True, null=True, to="product.metameasurement"
            ),
        ),
    ]
