# Generated by Django 5.0.6 on 2024-05-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_product_meta_measurement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="total_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
