# Generated by Django 5.0.6 on 2024-05-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
